Repository andoriyaprashant/DevDocsHub, pull requests merged in 2024-10, with the labels that each got.

#17 Update README.md
  README.md
Labels: documentation, gssoc-ext, level1

#29 Contributing.md
  Contributing.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#36 Adding issue and pull request template add, Fixed #28
  .github/ISSUE TEMPLATE/issue_template.md
  .github/PULL REQUEST TEMPLATE/pull_request_template.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#41 .gitignore added successfully
  .gitignore
Labels: gssoc-ext, level1, hacktoberfest-accepted

#63 fix-activate-script
  venv/Scripts/activate
Labels: gssoc-ext, level2, hacktoberfest-accepted

#81 issue#42 solved , css refactored
  .DS_Store
  DevDocsHub/settings.py
  Docs/.DS_Store
  Docs/templates/base.html
  Docs/templates/css/base.css
  Docs/templates/css/docs_list.css
  Docs/templates/css/home.css
  Docs/templates/docs_list.html
  Docs/templates/html/base.html
  Docs/templates/html/docs_list.html
  Docs/templates/html/home.html
Labels: gssoc-ext, level2, hacktoberfest-accepted
